create sequence SEQUENCEHISTORIQUE
	maxvalue 9999999
/

create sequence SEQUENTITEACTION
	maxvalue 9999999999
/

create sequence SEQUENTITEDESIGN
	maxvalue 9999999999
/

create sequence SEQUENTITEFICHIER
	maxvalue 9999999999
/

create sequence SEQUENTITESQL
	maxvalue 9999999999
/

create sequence SEQUENCEDOMAINE
	maxvalue 9999999
/

create table BONLIVRAISON
(
	NUMJIRA VARCHAR2(255) not null
		primary key,
	STATUT VARCHAR2(255),
	DATECREATION DATE,
	DESCRIPTION VARCHAR2(255),
	DOMAINE VARCHAR2(255),
	LIVRAISONNUMLIVRAISON VARCHAR2(255) not null,
	USERIDRH VARCHAR2(6) not null,
	PRET VARCHAR2(10) default NULL,
	DATEMODIF TIMESTAMP(6),
	AUTEURMODIF VARCHAR2(6),
	SOURCE VARCHAR2(20)
)
/

create table ENTITEACTION
(
	IDENTITE NUMBER(10) not null
		primary key,
	TYPEACTION VARCHAR2(25),
	CODEENTITEAC VARCHAR2(25),
	CODEENTITEMERE VARCHAR2(25),
	TYPEENTITEMERE VARCHAR2(25),
	NOMPROCESS VARCHAR2(25),
	RADICALPROCESS VARCHAR2(25),
	TEMOINFORCAGE VARCHAR2(10),
	PROGRAMME VARCHAR2(25),
	COMMENTAIRE VARCHAR2(1000),
	ENTITEDESIGNIDENTITE NUMBER(10) not null,
	DATECREATION TIMESTAMP(6),
	AUTEUR VARCHAR2(6),
	DATEMODIF TIMESTAMP(6),
	AUTEURMODIF VARCHAR2(6)
)
/

create table ENTITEDESIGN
(
	IDENTITE NUMBER(10) not null
		primary key,
	DOMAINE VARCHAR2(25),
	NOM VARCHAR2(255),
	TYPEDESIGN VARCHAR2(25),
	COMMENTAIRETECHNIQUE VARCHAR2(1000),
	COMMENTAIREFONCTIONNEL VARCHAR2(1000),
	NUMHPQC VARCHAR2(255),
	LIVRER VARCHAR2(10) default '0',
	BONLIVRAISONNUMJIRA VARCHAR2(255) not null
		constraint FK_BONLIVRAISON_ENTITEDESIGN
			references BONLIVRAISON
				on delete cascade,
	USERIDRH VARCHAR2(6),
	LASTUPDATEIDRH VARCHAR2(6),
	DATECREATION TIMESTAMP(6),
	DATEMODIF TIMESTAMP(6),
	REPORT VARCHAR2(20)
)
/

alter table ENTITEACTION
	add constraint FK_ENTITEDESIGN
		foreign key (ENTITEDESIGNIDENTITE) references ENTITEDESIGN
			on delete cascade
/

create table ENTITEFICHIER
(
	IDENTITE NUMBER(10) not null
		primary key,
	DOMAINE VARCHAR2(25),
	NOMFICHIER VARCHAR2(255),
	CHEMIN VARCHAR2(50),
	NUMVERSION NUMBER(11),
	COMMENTAIRETECHNIQUE VARCHAR2(1000),
	COMMENTAIREFONCTIONNEL VARCHAR2(1000),
	NUMHPQC VARCHAR2(255),
	BONLIVRAISONNUMJIRA VARCHAR2(255) not null
		constraint FK_BONLIVRAISON_ENTITEFICHIER
			references BONLIVRAISON
				on delete cascade,
	LASTUPDATEIDRH VARCHAR2(6),
	USERIDRH VARCHAR2(6),
	DATECREATION TIMESTAMP(6),
	DATEMODIF TIMESTAMP(6),
	REPORT VARCHAR2(20),
	ACONF VARCHAR2(20)
)
/

create table ENTITESQL
(
	IDENTITE NUMBER(10) not null
		primary key,
	DOMAINE VARCHAR2(25),
	TYPESQL VARCHAR2(25),
	NOMPROCESS VARCHAR2(25),
	ORDRESQL VARCHAR2(4000),
	ORDRESQLVIDAGE VARCHAR2(1000),
	COMMENTAIRETECHNIQUE VARCHAR2(1000),
	COMMENTAIREFONCTIONNEL VARCHAR2(1000),
	NUMHPQC VARCHAR2(255),
	BONLIVRAISONNUMJIRA VARCHAR2(255) not null
		constraint FK_BONLIVRAISON_ENTITESQL
			references BONLIVRAISON
				on delete cascade,
	USERIDRH VARCHAR2(6),
	LASTUPDATEIDRH VARCHAR2(6),
	DATECREATION TIMESTAMP(6),
	DATEMODIF TIMESTAMP(6),
	REPORT VARCHAR2(20)
)
/

create table ENVIRONNEMENT
(
	NOMENVIRONNEMENT VARCHAR2(25) not null
		primary key,
	DESCRIPTION VARCHAR2(255),
	COMPILABLE NUMBER(11)
)
/

create table HISTORIQUE
(
	IDRH VARCHAR2(6),
	ACTION VARCHAR2(255),
	NOM VARCHAR2(255),
	TYPE VARCHAR2(255),
	DATEACTION TIMESTAMP(6),
	ID NUMBER not null
		constraint HISTORIQUE_PK
			primary key,
	BONLIVRAISON VARCHAR2(255),
	ACTIONMANUELLE VARCHAR2(255)
)
/

create table LIVRAISON
(
	NUMLIVRAISON VARCHAR2(25) not null
		primary key,
	DATELIVRAISON TIMESTAMP(6),
	ETATLIVRAISON VARCHAR2(20),
	ENVSOURCE VARCHAR2(25) not null
		constraint SOURCE
			references ENVIRONNEMENT
				on delete cascade,
	ENVCIBLE VARCHAR2(25) not null
		constraint CIBLE
			references ENVIRONNEMENT
				on delete cascade
)
/

create table DOMAINE
(
	ID NUMBER not null
		constraint DOMAINE_PK
			primary key,
	NOM VARCHAR2(20),
	CODLIV VARCHAR2(20),
	LETTRELIV VARCHAR2(20),
	DESCRIPTION VARCHAR2(20)
)
/

create table REDMINE
(
	NUMERO NUMBER not null
		constraint TABLE1_PK
			primary key,
	NOM VARCHAR2(255),
	DATECREATION DATE,
	DATELIVRAISON DATE,
	DESCRIPTION VARCHAR2(255),
	BONLIVRAISON VARCHAR2(255) not null
		constraint REDMINE_FK1
			references BONLIVRAISON
)
/

create table UTILISATEUR
(
	IDENTIFIANT VARCHAR2(6 char) not null
		primary key,
	MOTDEPASSE VARCHAR2(10 char),
	NOMUSER VARCHAR2(25 char),
	PRENOMUSER VARCHAR2(25 char),
	ROLE VARCHAR2(25 char) not null
)
/

